# Generated by Django 5.1.5 on 2025-01-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='currencystate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fivehundred', models.IntegerField(default=0)),
                ('twohundred', models.IntegerField(default=0)),
                ('onehundred', models.IntegerField(default=0)),
                ('fifty', models.IntegerField(default=0)),
                ('twenty', models.IntegerField(default=0)),
                ('ten', models.IntegerField(default=0)),
                ('five', models.IntegerField(default=0)),
                ('two', models.IntegerField(default=0)),
                ('one', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='templist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('department_name', models.CharField(max_length=30)),
                ('month', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
                ('note', models.TextField()),
            ],
        ),
    ]
